name: Check for plugin updates

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Check for updates
        id: check-for-updates
        run: |
          sbt updateChecker/run
      - name: Create a pull request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Automatic update of the plugin versions
          body: ${{ steps.check-for-updates.outputs.pr-body }}
          commit-message: Automatic update of the plugin versions
          labels: automatic
          branch: automatic-plugins-update
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
