name: Check for plugin updates

on:
  push:
    branches: [master]
  schedule:
    - cron: "* */6 * * *"
  workflow_dispatch:

jobs:
  prepare-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Check for updates
        run: |
          sbt updateChecker/run
      - name: Create a pull request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Automatic update of the plugin versions
          body: This pull request was automatically opened, because updated versions of the plugin dependencies became available.
          commit-message: Automatic update of the plugin versions
          labels: automatic
          branch: automatic-plugins-update