name: Prepare the base container image

on: workflow_dispatch

jobs:
  prepare-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: odisseus
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Remove redundant packages
        run: |
          df -h
          #TODO find out the packages that own these files and uninstall them properly
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/share/swift
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/hostedtoolcache
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/az
          df -h
      - name: Prepare the image
        run: |
          ci/build_deps_img.sh
          docker images
      - name: Environment checks
        if: always()
        run: |
          df -h
          du -c -h --max-depth=4 --time --threshold=500M / 2> >(grep -v 'Permission denied') || true