name: Manual Build

on: workflow_dispatch

jobs:
  bar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Remove redundant packages
        run: |
          df -h
          #TODO find out the packages that own these files and uninstall them properly
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/share/swift
          sudo rm -rf /usr/local/lib/android
          df -h
      - name: Sanity check
        run: |
          ls -lZ
          docker --version
          df -h
      - name: Environment checks
        if: always()
        run: |
          df -h
          du -c -h --max-depth=4 --time --threshold=500M / || true